openapi: 3.0.1
info:
  title: Product Details Service
  description: Microservice for providing details of a product
  version: "1.1"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /product-details/updateProduct/{id}:
    put:
      tags:
      - product-details-controller
      operationId: updateProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDetails'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /product-details/addProduct:
    post:
      tags:
      - product-details-controller
      operationId: saveProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductDetails'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /product-details:
    get:
      tags:
      - product-details-controller
      operationId: getProducts
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductDetails'
  /product-details/getProduct/{id}:
    get:
      tags:
      - product-details-controller
      operationId: getProductById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ProductDetails'
  /product-details/deleteProduct/{id}:
    delete:
      tags:
      - product-details-controller
      operationId: deleteProduct
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    ProductDetails:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        quantity:
          type: integer
          format: int64
        price:
          type: integer
          format: int64
